import { useQuery } from '@tanstack/react-query'
import axios from 'axios'
import { useMemo, useState } from 'react'
import Card from '../components/Card'
import FormField from '../components/FormField'

interface Post {
	id: string
	name: string
	prompt: string
	image: string
}

const HomePage = () => {
	const [searchText, setSearchText] = useState('')

	const { data, isLoading, isError } = useQuery({
		queryKey: ['posts'],
		queryFn: async () => {
			const { data } = await axios.get('/api/posts')
			return data
		},
	})
	const imageFilter = useMemo(() => {
		return data?.filter((post: Post) => {
			return (
				searchText.trim() === '' ||
				post.prompt
					.trim()
					.toUpperCase()
					.includes(searchText.trim().toUpperCase()) ||
				post.name.toUpperCase().trim().includes(searchText.trim().toUpperCase())
			)
		})
	}, [data, searchText])

	return (
		<section className="max-w-7xl mx-auto">
			<div>
				<h1 className="font-extrabold text-[#222328] text-[32px]">
					The Community Showcase
				</h1>
				<p className="mt-2 text-[#666e75] text-[14px] max-w-[700px]">
					Browse through a collection of imaginative and visually stunning
					images generated by DALL-E AI
				</p>
			</div>
			<div className="mt-10">
				<FormField
					labelName="Search posts"
					inputType="text"
					name="text"
					placeholder="Search something..."
					value={searchText}
					setValue={setSearchText}
				/>
			</div>
			<div className="mt-7">
				{isLoading ? (
					<h3>Loading...</h3>
				) : isError ? (
					<h3>Something Wrong...</h3>
				) : data.length ? (
					<div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
						{imageFilter.length ? (
							imageFilter.map((post: Post) => <Card key={post.id} {...post} />)
						) : (
							<h3>No Search Results Found</h3>
						)}
					</div>
				) : (
					<h3>No Posts Yet</h3>
				)}
			</div>
		</section>
	)
}

export default HomePage
